config/routes.rb
JuniorWay::Application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: 'sessions' }

  root to: 'posts#index'

  resources :posts, param: :url_link do
    collection do
      resource :change_state, only: [:update], module: 'posts'
    end
  end

  resources :subscriptions, only: [:index, :create, :destroy] do
    get 'send_reminder', on: :collection
    get 'delete_notifier', on: :collection
  end

  resources :tags
  resource :search, only: [:show], module: 'posts'

  get 'sitemap.xml' => 'sitemap#index', defaults: { format: 'xml' }
end

app/views/shared/_admin.html.erb
<% if current_user %>
  <div id='sign_out'>
    <%= link_to 'Create new post', new_post_path %>
    /
    <%= link_to 'Subscriptions', subscriptions_path %>
    /
    <%= link_to 'Tags', tags_path %>
    /
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
  </div>
<% end %>

app/views/shared/_comments_count.html.erb
<script type='text/javascript'>
  var disqus_shortname = '<%= Post::DISQUS_SHORTNAME %>';

  (function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
  }());
</script>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, message| %>
  <div id='flash_message_notification' class="alert alert-<%= name == 'notice' ? 'success' : 'alert' %>">
    <strong><%= message %></strong>
  </div>
<% end %>

app/views/shared/_no_match_criterias.html.erb
<article class='post no_match_criteria'>
  <p>К сожалению, По вашему запросу статей не найдено. <%= link_to 'Сбросить?', root_path %></p>
</article>