config/routes.rb
JuniorWay::Application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: 'sessions' }

  root to: 'posts#index'

  resources :posts, param: :url_link do
    collection do
      resource :change_state, only: [:update], module: 'posts'
    end
  end

  resources :subscriptions, only: [:index, :create, :destroy] do
    get 'send_reminder', on: :collection
    get 'delete_notifier', on: :collection
  end

  resources :tags
  resource :search, only: [:show], module: 'posts'

  get 'sitemap.xml' => 'sitemap#index', defaults: { format: 'xml' }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts, association_foreign_key: :post_id

  validates :name, presence: true

  default_scope { order('priority', 'name') }

  # scope :by_name_and_priority, -> { order('priority', 'name') }
  # default_scope by_name_and_priority

  PRIORITY_RANGE = 1..100

  def self.reject_blank_from param
    param[:tag_ids] = param[:tag_ids].reject(&:empty?)
    param
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tags_params)

    if @tag.save
      redirect_to tags_path, notice: 'Tag created'
    else
      render 'new'
    end
  end

  def edit
    @tag = Tag.find(params[:id])
    render :new
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.update_attributes(tags_params)

    redirect_to tags_path
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path, notice: 'Tag was deleted!'
  end

  private
  def tags_params
    params.require(:tag).permit( :name, :priority )
  end
end

app/views/tags/_tag.html.erb
<tr>
  <td><%= tag.name %></td>
  <td><%= tag.priority %></td>
  <td>
    <%= link_to 'Edit', edit_tag_path(tag.id), class: 'btn btn-primary' %>
  </td>
  <td>
    <%= link_to 'Delete', tag_path(tag.id), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-danger'  %>
  </td>
</tr>

app/views/tags/index.html.erb
<div class='admin_pages'>
  <blockquote>
    <h3>Теги:</h3>
  </blockquote>

  <table class='table table-striped table-bordered'>
    <tr>
      <th style='width: 150px'>Tags name</th>
      <th style='width: 150px'>Priority</th>
      <th style='width: 50px'>Edit</th>
      <th style='width: 50px'>Destroy</th>
    </tr>
    <tbody>
      <%= render @tags %>
    </tbody>
  </table>

  <%= link_to 'Add Tag', new_tag_path, class: 'btn btn-primary' %>
</div>

app/views/tags/new.html.erb
<legend><h3>Create new tag:</h3></legend>

<div>
  <%= form_for @tag do |f| %>

    <div class='control-group'>
      <div class='controls'>
        <div class='input-prepend'>
          <span class='add-on'><i class='icon-th-list'></i></span>
          <%= f.text_field :name, placeholder: 'Tag', autofocus: true %>
        </div>
      </div>
    </div>

    <div class='control-group'>
      <div class='controls'>
        <div class='input-prepend'>
          <span class='add-on'><i class='icon-th-list'></i></span>
          <%= f.select :priority, Tag::PRIORITY_RANGE, selected: f.object.priority, prompt: 'Select priority' %>
        </div>
      </div>
    </div>

    <div class='control-group'>
      <div class='controls'>
        <%= f.submit 'Add', class: 'btn btn-success' %>
      </div>
    </div>

  <% end %>
</div>

<%= link_to 'All tags', tags_path, class: 'btn btn-inverse btn_back' %>