config/routes.rb
JuniorWay::Application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: 'sessions' }

  root to: 'posts#index'

  resources :posts, param: :url_link do
    collection do
      resource :change_state, only: [:update], module: 'posts'
    end
  end

  resources :subscriptions, only: [:index, :create, :destroy] do
    get 'send_reminder', on: :collection
    get 'delete_notifier', on: :collection
  end

  resources :tags
  resource :search, only: [:show], module: 'posts'

  get 'sitemap.xml' => 'sitemap#index', defaults: { format: 'xml' }
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  validates :last_id, numericality: true
  validates :email, :last_id, presence: true
  validates :email, length: { minimum: 7, maximum: 254 }

  scope :get_unconfirmed, ->(id) { where('last_id < ?', id) }

  def self.send_notification_with id
    subscribers = Subscription.get_unconfirmed(id)

    subscribers.each do |subscriber|
      SubscriptionNotifier.notify(subscriber.email).deliver
      subscriber.update_attribute(:last_id, id)
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!, only: [:index]

  def index
    @subscriptions = Subscription.all
  end

  def create
    subscription = Subscription.new(subscription_params.merge(last_id: find_last_id))

    if subscription.save
      flash[:notice] = 'Подписка оформленна!'
    else
      flash[:alert] = subscription.errors.full_messages.join(', ')
    end

    redirect_to root_path
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    redirect_to subscriptions_path, notice: 'Subscription was deleted!'
  end

  def send_reminder
    last_id = Post.get_last_availible_id
    Subscription.send_notification_with(last_id)

    redirect_to subscriptions_path, notice: 'Subscription was sent!'
  end

  def delete_notifier
    subscriber = Subscription.where(email: params[:email]).first
    subscriber.delete

    redirect_to root_path, notice: 'Подписка удалена!'
  end

  private
  def subscription_params
    params.require(:subscription).permit( :email, :last_id )
  end

  def find_last_id
    Post.available_for(current_user).maximum(:id)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_subscription.html.erb
<tr>
  <td><%= subscription.id %></td>
  <td><%= subscription.email %></td>
  <td><%= subscription.last_id %></td>
  <td>
    <%= link_to 'delete', subscription_path(subscription), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/subscriptions/index.html.erb
<div class='admin_pages'>
  <blockquote>
    <h3>Подписки:</h3>
  </blockquote>

  <table class='table table-striped table-bordered'>
    <tr>
      <th style='width: 10%'>#</th>
      <th style='width: 50%'>Email</th>
      <th style='width: 30%'>Last Post Id</th>
      <th style='width: 20%'>Actions</th>
    </tr>
    <tbody>
      <%= render @subscriptions %>
    </tbody>
  </table>

  <%= link_to 'Send Reminders', send_reminder_subscriptions_path, data: { confirm: 'Вы уверены?' }, class: 'btn btn-small btn-primary' %>
</div>