config/routes.rb
JuniorWay::Application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: 'sessions' }

  root to: 'posts#index'

  resources :posts, param: :url_link do
    collection do
      resource :change_state, only: [:update], module: 'posts'
    end
  end

  resources :subscriptions, only: [:index, :create, :destroy] do
    get 'send_reminder', on: :collection
    get 'delete_notifier', on: :collection
  end

  resources :tags
  resource :search, only: [:show], module: 'posts'

  get 'sitemap.xml' => 'sitemap#index', defaults: { format: 'xml' }
end

app/views/shared/meta/_index.html.erb
<% content_for :meta do %>
  <meta content="Rails Junior" name="title" />
  <meta content="Rails Junior: Ruby on Rails блог на русском языке,
  созданный для изучения веб-разработки. Оригинальные статьи, выдержки из книг по Rуby и Rails, HTML5, CSS3, JavaScript и т.д.
  Здесь вы найдете много различной информации о Rails." name="description" />
  <meta content="
    Rails, Junior, Ruby on Rails, Ruby, ruby on rails на русском, sinatra,
    framework, Rails3, Rails4, Rails 4.0, руководство, начинающим, manual, мануал,
    справочник, примеры, Руби, рельсы" name="keywords"
  />

  <meta content="Rails Junior" property="og:title" />
  <meta content="articles" property="og:type" />
  <meta content="<%= posts_url %>" name="og:url">
  <meta content="rails-junior.com" name="og:site_name">
<% end %>

app/views/shared/meta/_show.html.erb
<% content_for :meta do %>
  <meta content="<%= post.title %>" name="title">
  <meta content="<%= post.body_title %>" name="description">
  <meta content="<%= combine(post.tags) %>" name="tags">
  <meta content="<%= post.meta %>" name="keywords">

  <meta content="rails-junior.com" name="og:site_name">
  <meta content="<%= post.title %>" name="og:title">
  <meta content="article" name="og:type">
  <meta content="<%= post_url(post) %>" name="og:url">
  <meta content="<%= post.title_img %>" name="og:image">
  <meta content="<%= post.body_title %>" name="og:description">
<% end %>